// AUTO-GENERATED — run scratch/gen-articles-meta.cjs to regenerate.
// Lightweight article index: ONLY metadata, NO JSX content.
// Import this instead of ArticlePage.tsx to avoid pulling 953KB into your bundle.

export interface ArticleMeta {
  slug: string;
  title: string;
  category: string;
  readTime: string;
  date: string;
  image: string;
  metaDescription: string;
}

/** All articles — newest first. */
export const ARTICLE_META: ArticleMeta[] = [
  {
    slug: "how-can-a-startup-figure-out-whether-its-content-is-being-picked-up-by-llms",
    title: "How Can a Startup Figure Out Whether Its Content Is Being Picked Up by LLMs?",
    category: "Strategy",
    readTime: "9 min read",
    date: "June 30, 2026",
    image: "/images/llm-content-pickup-thumbnail.webp",
    metaDescription: "How can a startup figure out whether its content is being picked up by LLMs? Run a prompt library across ChatGPT, Claude & Perplexity, track citations & AI referral traffic. Get a free AI visibility audit.",
  },
  {
    slug: "what-are-ai-seo-services",
    title: "What Are AI SEO Services? The 2026 Guide to Getting Cited by AI",
    category: "AI SEO",
    readTime: "13 min read",
    date: "June 25, 2026",
    image: "/images/article-what-are-ai-seo-services.webp",
    metaDescription: "What are AI SEO services? AI SEO services optimize your brand to be cited in ChatGPT, Gemini, Perplexity & Google AI Overviews. See types, costs & ROI — book a free AI visibility audit.",
  },
  {
    slug: "introducing-open-knowledge-format-why-it-matters-for-ai-ready-businesses",
    title: "Introducing the Open Knowledge Format: Why It Matters for AI-Ready Businesses",
    category: "Strategy",
    readTime: "5 min read",
    date: "June 17, 2026",
    image: "https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=1200&q=80",
    metaDescription: "Google Cloud's new open spec, OKF, for representing knowledge as a portable file-system hierarchy of markdown and YAML.",
  },
  {
    slug: "multi-location-websites-for-franchises",
    title: "Multi Location Websites for Franchises: The 2026 Web Architecture Playbook",
    category: "Local SEO",
    readTime: "10 min read",
    date: "June 13, 2026",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&q=80",
    metaDescription: "A technical guide to multi-location websites for franchises. How to configure subdirectory URLs, prevent page cannibalization, and establish secure SEO governance.",
  },
  {
    slug: "b2b-organic-traffic-growth",
    title: "B2B Organic Traffic Growth: Why Traffic and Pipeline Decoupled in 2026 and What to Do About It",
    category: "Strategy",
    readTime: "14 min read",
    date: "May 26, 2026",
    image: "https://images.unsplash.com/photo-1531482615713-2afd69097998?w=1200&q=80",
    metaDescription: "How traffic and pipeline decoupled in B2B during 2025-2026, why the best B2B SEO programs are now growing less traffic on purpose, and what the new organic growth math actually looks like.",
  },
  {
    slug: "how-to-apply-behavioral-psychology-principles-to-high-ticket-b2b-landing-page-wireframes-to-decrease-friction",
    title: "How to Apply Behavioral Psychology Principles to High Ticket B2B Landing Page Wireframes to Decrease Friction",
    category: "Strategy",
    readTime: "12 min read",
    date: "June 12, 2026",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&q=80",
    metaDescription: "Learn how to apply behavioral psychology principles like the Fogg Behavior Model and Hick\\",
  },
  {
    slug: "gobiya-vs-enterprise-seo-agencies",
    title: "Enterprise SEO Agencies vs. Gobiya: The Honest Comparison",
    category: "Strategy",
    readTime: "14 min read",
    date: "June 3, 2026",
    image: "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=1200&q=80",
    metaDescription: "We compare enterprise SEO agencies vs Gobiya across execution speed, GEO citation rates, pipeline attribution, and real ROI math for B2B brands.",
  },
  {
    slug: "how-do-b2b-companies-use-seo-to-generate-predictable-revenue",
    title: "B2B Pipeline Revenue: How B2B Companies Use SEO to Scale",
    category: "Strategy",
    readTime: "6 min read",
    date: "May 31, 2026",
    image: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=1200&q=80",
    metaDescription: "Learn how to connect search clusters to B2B pipeline revenue, map content to the buying committee, and scale inbound conversions.",
  },
  {
    slug: "what-data-sources-do-llms-crawl-to-verify-b2b-company-information",
    title: "LLM Company Verification: What Data Sources Do AI Bots Crawl?",
    category: "GEO",
    readTime: "8 min read",
    date: "June 3, 2026",
    image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1200&q=80",
    metaDescription: "Discover how ChatGPT and Claude handle LLM company verification by crawling Wikidata, LinkedIn, and review portals to establish trust.",
  },
  {
    slug: "what-is-the-difference-between-google-knowledge-graph-optimization-and-geo",
    title: "Knowledge Graph Optimization vs. GEO: Key Splits",
    category: "GEO",
    readTime: "8 min read",
    date: "June 4, 2026",
    image: "https://images.unsplash.com/photo-1553877522-43269d4ea984?w=1200&q=80",
    metaDescription: "Understand how Knowledge Graph optimization differs from GEO, how entity resolution works, and how to secure AI citation visibility.",
  },
  {
    slug: "chatgpt-vs-google-for-business-discovery",
    title: "ChatGPT vs Google Search: Customer Trends",
    category: "SEO",
    readTime: "12 min read",
    date: "May 29, 2026",
    image: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=1200&q=80",
    metaDescription: "Comparing ChatGPT vs Google search discovery rates. Learn how to optimize your brand footprint to win both AI summaries and clicks.",
  },
  {
    slug: "what-is-the-difference-between-a-manual-action-and-an-algorithmic-penalty",
    title: "Manual Action vs Algorithmic Penalty: Key Splits",
    category: "SEO",
    readTime: "9 min read",
    date: "May 29, 2026",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=1200&q=80",
    metaDescription: "Understand manual action vs algorithmic penalty differences, Search Console reports, and step-by-step diagnostic checklists for recovery.",
  },
  {
    slug: "what-is-generative-engine-optimization-and-how-does-it-work",
    title: "Generative Engine Optimization (GEO): RAG & AI Guide",
    category: "SEO",
    readTime: "10 min read",
    date: "May 30, 2026",
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&q=80",
    metaDescription: "A complete technical guide to Generative Engine Optimization (GEO). Learn how RAG-based AI search engines cite content and how to optimize.",
  },
  {
    slug: "google-manual-action-removal-agency-caused-penalty",
    title: "Google Manual Action Removal: Step-by-Step Penalty Recovery",
    category: "SEO",
    readTime: "10 min read",
    date: "May 27, 2026",
    image: "https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=1200&q=80",
    metaDescription: "Use our Google manual action removal checklist to audit link profiles, document cleanup, and submit a successful reconsideration appeal.",
  },
  {
    slug: "automated-b2b-sales-pipeline-seo",
    title: "B2B Sales Pipeline Automation: AI Citations",
    category: "Strategy",
    readTime: "12 min read",
    date: "May 25, 2026",
    image: "https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=1200&q=80",
    metaDescription: "Integrate B2B sales pipeline automation with search intent. Learn how AI citation share decides who gets on the buyer shortlist.",
  },
  {
    slug: "automated-lead-generation-seo",
    title: "Automated Lead Generation: Search Intent Mapping",
    category: "Strategy",
    readTime: "13 min read",
    date: "May 25, 2026",
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&q=80",
    metaDescription: "Set up automated lead generation by mapping high-intent search clusters to your B2B pipeline to drive closed sales, not just page views.",
  },
  {
    slug: "outbound-seo-prospecting",
    title: "Outbound SEO Prospecting: Timing Intent Signals",
    category: "Strategy",
    readTime: "12 min read",
    date: "May 25, 2026",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&q=80",
    metaDescription: "Use outbound SEO prospecting to monitor search intent triggers. Learn how to pitch buyers at the exact moment they search for your service.",
  },
  {
    slug: "b2b-sales-pipeline-automation",
    title: "B2B Sales Pipeline Automation: CRM Pipelines",
    category: "Strategy",
    readTime: "13 min read",
    date: "May 25, 2026",
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=1200&q=80",
    metaDescription: "Configure B2B sales pipeline automation workflows. Learn how to connect search intent, lead data enrichment, and automated email campaigns.",
  },
  {
    slug: "best-seo-agency-for-b2b-brands",
    title: "Best SEO Agency for B2B: Evaluation Checklist",
    category: "Strategy",
    readTime: "11 min read",
    date: "May 25, 2026",
    image: "https://images.unsplash.com/photo-1531482615713-2afd69097998?w=1200&q=80",
    metaDescription: "How to select the best SEO agency for B2B brands. Follow our evaluation checklist to verify technical authority, case studies, and contracts.",
  },
  {
    slug: "seo-for-b2b-lead-generation",
    title: "SEO for B2B Lead Generation: Committee Mapping",
    category: "Strategy",
    readTime: "14 min read",
    date: "May 25, 2026",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&q=80",
    metaDescription: "Optimize SEO for B2B lead generation by mapping content to the buying committee stakeholders to increase deal velocity and close rates.",
  },
  {
    slug: "local-seo",
    title: "Local SEO Strategy: 2026 Map Pack Playbook",
    category: "Local SEO",
    readTime: "13 min read",
    date: "May 26, 2026",
    image: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=1200&q=80",
    metaDescription: "Deploy an advanced local SEO strategy to dominate the Google 3-Pack, optimize schema markup, and capture geographic searches.",
  },
  {
    slug: "local-seo-explained",
    title: "Local SEO Explained: Operational Consistency Playbook",
    category: "Local SEO",
    readTime: "10 min read",
    date: "May 27, 2026",
    image: "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=1200&q=80",
    metaDescription: "Our local SEO explained guide shows how to run weekly optimizations, review acquisitions, and local profile updates to secure Map Pack dominance.",
  },
  {
    slug: "multi-location-seo-website-structure",
    title: "Multi-Location SEO Website Structure: Hierarchy Playbook",
    category: "Local SEO",
    readTime: "12 min read",
    date: "May 27, 2026",
    image: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=1200&q=80",
    metaDescription: "Learn to structure a multi-location SEO website structure that prevents cannibalization, consolidates link equity, and ranks every city page.",
  },
  {
    slug: "best-website-structure-multiple-locations-different-cities",
    title: "Best Website Structure Multiple Locations: Silo Setup",
    category: "Local SEO",
    readTime: "14 min read",
    date: "May 28, 2026",
    image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1200&q=80",
    metaDescription: "Our guide details the best website structure multiple locations setup. Compare subdirectory vs subdomain hierarchies for localized organic growth.",
  },
  {
    slug: "can-a-site-fully-recover-from-a-google-core-update",
    title: "Google Core Update Recovery: Full Traffic Restoration",
    category: "SEO",
    readTime: "15 min read",
    date: "May 28, 2026",
    image: "https://images.unsplash.com/photo-1553877522-43269d4ea984?w=1200&q=80",
    metaDescription: "Our Google core update recovery guide details the timeline, content pruning strategies, and quality updates needed to restore search traffic.",
  },
  {
    slug: "google-business-profile-optimization",
    title: "Google Business Profile Optimization: Recovery & Audits",
    category: "Local SEO",
    readTime: "16 min read",
    date: "May 28, 2026",
    image: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=1200&q=80",
    metaDescription: "Learn our Google Business Profile optimization checklist to recover suspended profiles, appeal algorithmic soft bans, and verify map listings.",
  },
  {
    slug: "b2b-seo-agency",
    title: "B2B SEO Agency: Pipeline Attribution Guide",
    category: "Strategy",
    readTime: "14 min read",
    date: "May 27, 2026",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=1200&q=80",
    metaDescription: "Partner with a B2B SEO agency built around pipeline value, not just search volume. Verify our committee mapping and conversion playbooks.",
  },
  {
    slug: "seo-case-study-traffic-recovery",
    title: "SEO Case Study Traffic Recovery: 320% Growth",
    category: "SEO",
    readTime: "12 min read",
    date: "May 31, 2026",
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&q=80",
    metaDescription: "A forensic SEO case study on traffic recovery after Google\\",
  },
  {
    slug: "are-ai-search-engines-scraping-hidden-api-data-or-public-html-text-blocks",
    title: "AI Search Scraping: API vs HTML Blocks",
    category: "GEO",
    readTime: "10 min read",
    date: "June 4, 2026",
    image: "https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=1200&q=80",
    metaDescription: "Understand how AI search scraping works. Learn why AI crawlers bypass JavaScript APIs and read raw public HTML blocks instead.",
  },
  {
    slug: "brand-entity-extraction-perception-drift",
    title: "Brand Entity Extraction & Perception Drift: Knowledge Graph Guide",
    category: "Knowledge Graph Intelligence",
    readTime: "12 min read",
    date: "June 10, 2026",
    image: "https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=1200&q=80",
    metaDescription: "How brand entity extraction works across Google, Bing, Wikidata, and LLM knowledge graphs — and how to detect and correct perception drift before it costs you AI citations.",
  },
  {
    slug: "dental-seo-agency",
    title: "Dental SEO Agency Checklist: Red Flags and KPIs to Watch",
    category: "Local SEO",
    readTime: "14 min read",
    date: "June 7, 2026",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&q=80",
    metaDescription: "Avoid costly hiring mistakes. Use our comprehensive evaluation checklist for dental SEO agencies, covering contract traps, KPIs, case study audits, and ROI benchmarks.",
  },
];

/** Keyed by slug for O(1) lookup. */
export const ARTICLE_META_MAP: Record<string, ArticleMeta> = Object.fromEntries(
  ARTICLE_META.map(a => [a.slug, a])
);
